In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.io
from scipy.io import wavfile                                                                                                            
from scipy import signal

In [2]:
%matplotlib inline

# Q1
Take a 5 second sample of your speech, sampled at 8 kHz, and perform linear predictive coding with predictor lengths 4,8,16 on it. Calculate the processing gain in each case.

In [3]:
samplerate, data = wavfile.read("./output.wav")

In [4]:
secs = data.shape[0]/samplerate

In [5]:
len(data)

16000

In [20]:
sampdata = data[:,0] 

In [21]:
l = len(data)

In [22]:
def autocorr(x):
    '''numpy.correlate, non partial'''
    mean=x.mean()
    var=np.var(x)
    xp=x-mean
    # corr=np.correlate(xp,xp,'full')[len(x)-1:]/var/len(x)
    corr=np.correlate(xp,xp,'full')/var/len(x)

    return corr

In [23]:
r = autocorr(sampdata)

In [24]:
r.shape

(31999,)

In [25]:
r[l-1:]

array([ 9.9999988e-01,  8.5632414e-01,  6.9186145e-01, ...,
       -1.3692649e-07, -9.7903218e-08, -4.4938545e-08], dtype=float32)

In [38]:
p = 8

In [39]:
R = np.zeros((p,p))

In [40]:
q = np.transpose(r[l:l+p])

In [41]:
q

array([ 0.85632414,  0.69186145,  0.62934244,  0.47240102,  0.30878338,
        0.20490177, -0.00088449, -0.19655399], dtype=float32)

In [42]:
for i in range(p):
    R[i,:] = r[l-1-i:l-1+p-i]

In [43]:
R

array([[ 9.99999881e-01,  8.56324136e-01,  6.91861451e-01,
         6.29342437e-01,  4.72401023e-01,  3.08783382e-01,
         2.04901770e-01, -8.84494395e-04],
       [ 8.56324136e-01,  9.99999881e-01,  8.56324136e-01,
         6.91861451e-01,  6.29342437e-01,  4.72401023e-01,
         3.08783382e-01,  2.04901770e-01],
       [ 6.91861451e-01,  8.56324136e-01,  9.99999881e-01,
         8.56324136e-01,  6.91861451e-01,  6.29342437e-01,
         4.72401023e-01,  3.08783382e-01],
       [ 6.29342437e-01,  6.91861451e-01,  8.56324136e-01,
         9.99999881e-01,  8.56324136e-01,  6.91861451e-01,
         6.29342437e-01,  4.72401023e-01],
       [ 4.72401023e-01,  6.29342437e-01,  6.91861451e-01,
         8.56324136e-01,  9.99999881e-01,  8.56324136e-01,
         6.91861451e-01,  6.29342437e-01],
       [ 3.08783382e-01,  4.72401023e-01,  6.29342437e-01,
         6.91861451e-01,  8.56324136e-01,  9.99999881e-01,
         8.56324136e-01,  6.91861451e-01],
       [ 2.04901770e-01,  3.087833

In [44]:
w = np.linalg.solve(R,q)

In [45]:
w.shape

(8,)

In [46]:
def gain(x,R,w):
    var = np.var(x)
    RW = np.dot(R,w)
    
    return var/(var-np.dot(w.T,RW))

In [35]:
gain(sampdata,R,w) # 16

-0.013082294387899039

In [36]:
gain(sampdata,R,w) # 4

-0.013082294387899039

In [47]:
gain(sampdata,R,w) # 8

-0.013082294387899039